In [1]:
import os
import sys
project_src = os.path.abspath('../outputs')
if project_src not in sys.path:
    sys.path.insert(0, project_src)

In [18]:
import pandas as pd

df_results = pd.read_csv('../outputs/batch_summary.csv')
df_results

,Ticker,Model,Breach Rate (%),Kupiec p-value,Avg Capital Reserved,Max Capital Reserved,Min Capital Reserved,Responsiveness (Std),Status
0,^GSPC,Neural Network,0.27%,0.0407,-3.42%,-4.24%,-2.57%,0.0013,❌ FAIL
1,^GSPC,"GARCH(1,1)",3.34%,0.0000,-1.80%,-6.61%,-0.78%,0.0072,❌ FAIL
2,^GSPC,Anchor NN,1.07%,0.8527,-2.44%,-7.14%,-1.93%,0.0046,✅ PASS
3,^GSPC,Historical VaR,1.34%,0.3527,-2.27%,-3.02%,-1.48%,0.0053,✅ PASS
4,BTC-USD,Neural Network,0.00%,0.0000,-10.69%,-16.44%,-9.99%,0.0086,❌ FAIL
5,BTC-USD,"GARCH(1,1)",2.78%,0.0000,-5.24%,-12.99%,-2.46%,0.0129,❌ FAIL
6,BTC-USD,Anchor NN,1.21%,0.4435,-6.26%,-8.85%,-4.11%,0.0091,✅ PASS
7,BTC-USD,Historical VaR,1.39%,0.2164,-5.93%,-7.11%,-5.07%,0.0061,✅ PASS
8,CLP=X,Neural Network,1.56%,0.1414,-2.27%,-4.02%,-1.64%,0.0032,✅ PASS
9,CLP=X,"GARCH(1,1)",1.82%,0.0293,-2.25%,-5.69%,-0.58%,0.0060,❌ FAIL
10,CLP=X,Anchor NN,1.56%,0.1414,-2.31%,-4.24%,-1.71%,0.0032,✅ PASS
11,CLP=X,Historical VaR,1.30%,0.3631,-2.28%,-2.86%,-1.80%,0.0020,✅ PASS
12,SQM,Neural Network,0.53%,0.2672,-8.43%,-8.77%,-8.00%,0.0011,✅ PASS
13,SQM,"GARCH(1,1)",2.01%,0.0143,-6.69%,-16.66%,-4.22%,0.0125,❌ FAIL
14,SQM,Anchor NN,0.94%,1.0000,-7.34%,-8.61%,-6.22%,0.0054,✅ PASS
15,SQM,Historical VaR,0.80%,0.7148,-7.44%,-10.03%,-5.65%,0.0104,✅ PASS
16,HG=F,Neural Network,1.87%,0.0252,-3.65%,-7.97%,-2.10%,0.0033,❌ FAIL
17,HG=F,"GARCH(1,1)",1.34%,0.3527,-3.93%,-14.08%,-2.06%,0.0152,✅ PASS
18,HG=F,Anchor NN,1.20%,0.5772,-4.05%,-39.81%,-2.70%,0.0163,✅ PASS
19,HG=F,Historical VaR,1.74%,0.0613,-4.03%,-5.43%,-2.38%,0.0102,✅ PASS
20,TSLA,Neural Network,0.94%,1.0000,-9.88%,-13.13%,-6.25%,0.0067,✅ PASS
21,TSLA,"GARCH(1,1)",2.01%,0.0143,-7.92%,-13.31%,-4.53%,0.0196,❌ FAIL
22,TSLA,Anchor NN,1.20%,0.5772,-8.73%,-12.24%,-6.08%,0.0147,✅ PASS
23,TSLA,Historical VaR,0.94%,1.0000,-9.49%,-12.06%,-6.83%,0.0106,✅ PASS
24,NVDA,Neural Network,0.94%,1.0000,-8.10%,-9.46%,-6.47%,0.0034,✅ PASS
25,NVDA,"GARCH(1,1)",2.54%,0.0003,-6.12%,-17.74%,-2.57%,0.0190,❌ FAIL
26,NVDA,Anchor NN,1.07%,0.8527,-6.95%,-10.13%,-5.17%,0.0103,✅ PASS
27,NVDA,Historical VaR,1.60%,0.0972,-7.12%,-9.54%,-4.49%,0.0157,✅ PASS
28,CL=F,Neural Network,0.94%,1.0000,-8.04%,-9.89%,-5.84%,0.0038,✅ PASS
29,CL=F,"GARCH(1,1)",2.81%,0.0000,-5.12%,-20.08%,-2.12%,0.0249,❌ FAIL
30,CL=F,Anchor NN,2.14%,0.0048,-5.45%,-10.00%,-3.77%,0.0120,❌ FAIL
31,CL=F,Historical VaR,1.74%,0.0613,-5.83%,-11.54%,-4.28%,0.0174,✅ PASS

In [19]:
fail_str = '❌ FAIL'
pass_str = '✅ PASS'

df_results['status_aux'] = 1
df_results.loc[df_results['Status'] == fail_str, 'status_aux'] = 0

df_results_pt = df_results.pivot_table(columns='Model', index='Ticker', values='status_aux')

In [20]:
df_results_pt = df_results_pt.astype(str)

df_results_pt[df_results_pt == '1.0'] = pass_str
df_results_pt[df_results_pt == '0.0'] = fail_str

df_results_pt

Model   Anchor NN GARCH(1,1) Historical VaR Neural Network
Ticker
BTC-USD    ✅ PASS     ❌ FAIL         ✅ PASS         ❌ FAIL
CL=F       ❌ FAIL     ❌ FAIL         ✅ PASS         ✅ PASS
CLP=X      ✅ PASS     ❌ FAIL         ✅ PASS         ✅ PASS
HG=F       ✅ PASS     ✅ PASS         ✅ PASS         ❌ FAIL
NVDA       ✅ PASS     ❌ FAIL         ✅ PASS         ✅ PASS
SQM        ✅ PASS     ❌ FAIL         ✅ PASS         ✅ PASS
TSLA       ✅ PASS     ❌ FAIL         ✅ PASS         ✅ PASS
^GSPC      ✅ PASS     ❌ FAIL         ✅ PASS         ❌ FAIL